engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
- phpqrcode/**/*
- phpqrcode/*
- qiniu/**/*
- qiniu/*
- JPush/**/*
- JPush/*
- picture/*
- js/jquery-1.11.2.min.js
