engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - interface/*
  - interface/**/*
  - receiver.php
exclude_paths:
- phpqrcode/**/*
- phpqrcode/*
- qiniu/**/*
- qiniu/*
- JPush/**/*
- JPush/*
- helper/*
- helper/**/*
- picture/*
- js/**/*
- js/*